### ISSUE TITLE
false: backscatterer.org listed in scams-and-phishing.txt

### ISSUE THREAD

**Issue by crssi** [infinitytec/blocklists#10]
Not sure why `backscatterer.org` should be listed in [scams-and-phishing.txt](https://github.com/infinitytec/blocklists/blob/master/scams-and-phishing.txt), since its just the opposite (that is, its for fighting against the spam/phish/scam).

**Comment by infinitytec** [comment]
Thanks for the feedback!

From what I have seen, this is part of Uceprotect, which is a [rather sketchy blocklist provider](https://en.wikipedia.org/wiki/Comparison_of_DNS_blacklists#Suspect_RBL_providers). This and some others were added with #9 and in some subsequent updates.

I will be more than happy to remove it and other Uceprotect domains if I can be convinced that it is a trustworthy source, but from what I have seen it should probably remain on the list, but at this time I'm going to leave it here.
