### ISSUE TITLE
Malformed line in scams-and-phising.txt

### ISSUE THREAD

**Issue by silentcreek** [infinitytec/blocklists#11]
Hi,

as of today, the scams-and-phising.txt list contains one line with white-space in-between two domain names. I assume these should have gone on two lines?

https://github.com/infinitytec/blocklists/blob/0d97cfa3ae44aa42a883534c65424b9ce38429b2/scams-and-phishing.txt#L4862

Cheers,

Timo

**Comment by infinitytec** [comment]
Should be good now! Thanks for the report!
