### ISSUE TITLE
Several non-domain entries

### ISSUE THREAD

**Issue by Knuschberkeks** [infinitytec/blocklists#14]
Hi, there are at least 5 domains on the Scams and Fishing list that can not be domains:
- groupm.è.to
- qzzjf.u
- www. groupm.è.to
- www.qzzjf.u
- www.è.to

**Comment by infinitytec** [comment]
I will look into these. I was aware that Pi-hole rejected them outright. Have they been causing any issues or just error messages for you?

**Comment by Knuschberkeks** [comment]
No just errors. Thought they might be typos or something like that (in which case something that should be blocked isn't.)

**Comment by infinitytec** [comment]
Nope, these I think came from fake GroupMe Support messages. I'll check to see if these were just obfuscation to try to get around automated filters.

**Comment by infinitytec** [comment]
Using DomainTools for lookup, I have seen that "è.to" appears as "xn--8ca.to" which is interesting. The registrar "tonic.to" confirms "è.to" is invalid, but "xn--8ca.to" is taken. Curiously, entering "xn--8ca.to" in a browser makes the URL field look like "è.to" in the URL bar!

The proper solution is probably to block both, although it does seem unlikely that "è.to" would actually get resolved in the first place!

Several registrars confirmed that "qzzjf.u" is not valid, and the closest match I can think of is "qzzjf.us" which does not seem registered, so I will remove "qzzjf.u" from the list.

**Comment by infinitytec** [comment]
These should be resolved.
