### ISSUE TITLE
False positive: A-GPS domain xtrapath2.izatcloud.net

### ISSUE THREAD

**Issue by HorayNarea** [infinitytec/blocklists#16]
https://github.com/infinitytec/blocklists/blob/fd4f9585e9e7e51a6bb39d049171a526ae880bc9/ads-and-trackers.txt#L52450

GPS-radios made by Qualcomm download assistance data from the domains `xtrapath{1,2,3}.izatcloud.net`, these are neither ads nor trackers.

**Comment by infinitytec** [comment]
Thanks! I will take a look at this ASAP. Is there any specific undesired behavior that is being seen by this being blocked?

**Comment by hagezi** [comment]
_"A-GPS is also used in emergencies"_
@infinitytec FYI: https://github.com/hagezi/dns-blocklists/issues/984

**Comment by infinitytec** [comment]
> _"A-GPS is also used in emergencies"_ @infinitytec FYI: [hagezi/dns-blocklists#984](https://github.com/hagezi/dns-blocklists/issues/984)

Ope. I will get this fixed!

**Comment by infinitytec** [comment]
This domain is now removed. Thanks!
