### ISSUE TITLE
Blocklist Cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [infinitytec/blocklists#17]
[i] Target: https://github.com/infinitytec/blocklists/raw/master/scams-and-phishing.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 22885 exact domains and 0 ABP-style domains (ignored 4 non-domain entries)
      Sample of non-domain entries:
        - "groupm.è.to"
        - "www.groupm.è.to"
        - "www.è.to"
        - "è.to"

**Comment by infinitytec** [comment]
Yep, I am aware of these. I'm not sure how, but somehow these are what appear in the address bar. I don't really know what to do with them, but removing them probably wouldn't hurt.

**Comment by AyanokojiK1yotaka** [comment]
I think hagezi can help you with that

**Comment by infinitytec** [comment]
Those domains have been removed.
