### ISSUE TITLE
graph.facebook.com needed for facebook functionality.

### ISSUE THREAD

**Issue by ClevyPasserby** [infinitytec/blocklists#19]
I use a personal merged adblock file collated from various sources, this being one of them. I did notice my messenger in my android not working so I checked my sources and found one of my sources containing [this](https://raw.githubusercontent.com/infinitytec/blocklists/master/ads-and-trackers.txt) having the said domain. I request you whitelist the domain for facebook functionality.

**Comment by infinitytec** [comment]
👍
