### ISSUE TITLE
Verify possible hosts

### ISSUE THREAD

**Issue by infinitytec** [infinitytec/blocklists#2]
If anyone has any information regarding any entries on the possible hosts list, please inform me here, so I can either add it to the appropriate list or remove it as a false positive.

**Comment by SergeAx** [comment]
Hi! I am working at FunCorp, company of iFunny.

ws-afb3a55b-8275-4c1e-aea8-309842798187.sendbird.com is a hostname created for iFunny by SendBird, SaaS platform for our chat. Behind it is their standard API - https://docs.sendbird.com/platform It is for chat, not for tracking.

**Comment by infinitytec** [comment]
Ah, thank you. I'll get that fixed!

**Comment by p1r473** [comment]
@infinitytec a151.g.akamai.net is a CNAME for rgom10-en.url.trendmicro.com
As such, blocking this host has broken Trend Micro AV.

**Comment by infinitytec** [comment]
> @infinitytec a151.g.akamai.net is a CNAME for rgom10-en.url.trendmicro.com
> As such, blocking this host has broken Trend Micro AV.

Awesome. Thanks. I will remove it!

**Comment by p1r473** [comment]
Thanks for the fast response!

**Comment by p1r473** [comment]
Regarding clientconfig.akamai.steamstatic.com,
This is used for static client configurations over akamai which is steams content distribution network. This includes serving configuration files for certain games. 
Also a CNAME for akacdn.valve.com.edgesuite.net which is a Valve CDN

**Comment by p1r473** [comment]
Regarding mobilecrashreporting.googleapis.com,
Its not so much telemetry as it is literally mobile app/OS crash reporting, literally
I believe this one is safe to block, as well, other blocklists block this one

**Comment by p1r473** [comment]
Regarding  osce11-0-en.url.trendmicro.com
It is used for my Trend Micro AV to initiate Smart Scans
https://success.trendmicro.com/solution/1113595-smartscan-unavailable-shows-up-and-agents-cannot-connect-to-the-global-scan-server-in-officescan
Safe to remove. Only one 545 (literally actually) other blocklist has this, and I have reported it there as well.
https://github.com/mkb2091/blockconvert/issues/30

**Comment by p1r473** [comment]
Regarding api.intelsa.intel.com
This is the API for Intel's Security Assistant.
APIs can be used for all sorts of functions. 
This one is also unique to your blocklist. I think this one is safe to let pass through.

**Comment by p1r473** [comment]
Regarding activity.windows.com
Many other blocklists blocking this one
However, some things will break:
> new Chromium Edge browser's sync feature doesn't work. Sync is relied on it.
> If blocked, no comment votes are possible in Windows Store.
https://github.com/crazy-max/WindowsSpyBlocker/issues/205

Safe to let through if you don't want to break things.

**Comment by infinitytec** [comment]
Closing. This has been rather static.
