### ISSUE TITLE
Report: new malware/phishing site

### ISSUE THREAD

**Issue by yokoffing** [infinitytec/blocklists#5]
`https://imgvieweriri.com/g/?5678565867953463634566=f7&look=mypal_hal&ure=https://instagram.fbkk9-2.fna.fbcdn.net/v/t51.2885-19/s150x150/69013703_644272702749406_7283768718696382464_n.jpg?_nc_ht=instagram.fbkk9-2.fna.fbcdn.net&_nc_ohc=yxXDm260USwAX9txkHS&oh=7171c70463001c681263dbb34948ac91&oe=5EF54B98`

The above is a newly registered domain (NRD) that tries to get the user to enter their Instagram credentials. Used in hacked Instagram accounts. Please add to your list :)

**Comment by infinitytec** [comment]
Will add! Thanks!
