### ISSUE TITLE
Don’t block t-online.de since this blocks the infrastructure of the German Corona Warn App

### ISSUE THREAD

**Issue by mhusar** [infinitytec/blocklists#6]
On my Android phone I now use [RethinkDNS](https://www.bravedns.com/) to block trackers and other domains. Today I observed that the domain svc90.main.px.t-online.de is blocked. The RethinkDNS app told me that the responsible block list was inifinitytec (scam and phishing).

This domain is used to by the German [Corona Warn App](https://www.coronawarn.app/en/) to help people to get warned when they met an infected person. It’s very likely that the domain is used to communicate with infrastructure of other Corona Apps in Europe. The app and its infrastructure are completely open source and anonymized. There are no problems with privacy at all.

Official Website: https://www.coronawarn.app/en/
German Federal Government: https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch
GitHub: https://github.com/corona-warn-app
Bug report on GitHub: https://github.com/corona-warn-app/cwa-app-android/issues/574 (svc90.main.px.t-online.de is blocked)
Wikipedia: https://en.wikipedia.org/wiki/Corona-Warn-App
Google Play: https://play.google.com/store/apps/details?id=de.rki.coronawarnapp
F-Droid: https://f-droid.org/de/packages/de.corona.tracing/ (degoogled fork)
Apple App Store: https://apps.apple.com/de/app/corona-warn-app/id1512595757

**Some background**

The website “[T-Online](https.//www.t-online.de) is Germany's biggest news portal, owned and published by digital multi-channel media company Ströer” ([Wikipedia](https://en.wikipedia.org/wiki/T-Online)). The domain [t-online.de](t-online.de) itself belongs to [Deutsche Telekom AG](https://www.telekom.de), which “is a German telecommunications company headquartered in Bonn and by revenue the largest telecommunications provider in Europe” ([Wikipedia](https://en.wikipedia.org/wiki/Deutsche_Telekom)). T-Online was a German ISP owned by Deutsche Telekom. In 2006, it was re-integrated into Deutsche Telekom. The only thing left is the news portal they sold to Ströer.

The domain [t-online.de](t-online.de) is still used by Deutsche Telekom, [T-Systems](https://www.t-systems.com/de/en) and maybe their mobile ISP, formerly known as T-Mobile. Deutsche Telekom also owns [T-Mobile US](https://www.t-mobile.com/).

Neither [www.t-online.de](https://www.t-online.de) nor [t-online.de](https://t-online.de) and all its subdomains are a scam or have anything to do with phishing. Please unblock these because it creates inconveniences for people living in Germany.

**Comment by infinitytec** [comment]
Thanks for the feedback! I have updated the list.
