### ISSUE TITLE
Youtube-Handling do not work

### ISSUE THREAD

**Issue by RichardBeisser** [infinitytec/blocklists#7]
Hello,

since google changed the design, the annoyance-blocklist doesnt handle the youtube-banners correctly.
YT ask you if you want to sign in to an account. The blocklist just suppresses that notice. Without answering the notice, you cannot play a video.

please fix this.

Thanks.

**Comment by infinitytec** [comment]
Thanks for letting me know!

I have removed the YouTube filters from the list, so that should solve the problem. Please let me know if any other problems come up.
